name: Generate ASCII Artwork

on: push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout Repo
      uses: actions/checkout@v4

    - name: Generate ASCII Artwork
      run: sudo apt-get install cowsay -y

    - name: Generate ASCII Artwork
      run: cowsay -f dragon 'Run for cover,I am a dragon .. rawr..' >> dragon.txt
    
    - name: checkout Repo files
      run: ls -lart

    - name: Test file exists
      run: grep -i 'dragon' dragon.txt
    
    - name: read files
      run: cat dragon.txt


